{"523f3d40ae6d12c7524eeb066d80122d":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"8146305b23f13402","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data_projext', port=443): Max retries exceeded with url: /api_1_0/conversation (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002157D458070>: Failed to resolve 'data_projext' ([Errno 11001] getaddrinfo failed)\"))","time":{"start":1731765262086,"stop":1731765264777,"duration":2691}}]},"4e8dace20dd8dd403de3a34def3296fe":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"dc84bc659ac0b637","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data_projext', port=443): Max retries exceeded with url: /api_1_0/conversation (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002157D05C7F0>: Failed to resolve 'data_projext' ([Errno 11001] getaddrinfo failed)\"))","time":{"start":1731765259110,"stop":1731765261847,"duration":2737}}]},"f4aaa326b47224e711609fb0443ae819":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"92109579f2c178d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data_projext', port=443): Max retries exceeded with url: /api_1_0/conversation (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002157D259840>: Failed to resolve 'data_projext' ([Errno 11001] getaddrinfo failed)\"))","time":{"start":1731765264875,"stop":1731765267571,"duration":2696}}]}}